--Fact table DDL

CREATE TABLE customer_profile_fact(
  sacc_items INT,
  work_orders INT,
  female_items INT,
  is_newsletter_subscriber TEXT,
  male_items INT,
  afterpay_payments INT,
  msite_orders INT,
  wftw_items INT,
  mapp_items INT,
  orders INT,
  cc_payments INT,
  curvy_items INT,
  paypal_payments INT,
  macc_items INT,
  cancels INT,
  revenue REAL,
  returns INT,
  other_collection_orders INT,
  parcelpoint_orders INT,
  customer_id TEXT,
  android_orders INT,
  days_since_last_order INT,
  vouchers INT,
  average_discount_used REAL,
  shipping_addresses INT,
  redpen_discount_used REAL,
  mftw_items INT,
  days_since_first_order INT,
  unisex_items INT,
  home_orders INT,
  coupon_discount_applied REAL,
  desktop_orders INT,
  ios_orders INT,
  apple_payments INT,
  wspt_items INT,
  wacc_items INT,
  items INT,
  mspt_items INT,
  devices INT,
  different_addresses INT,
  wapp_items INT,
  other_device_orders INT,
  average_discount_onoffer REAL
);
